cp -r ~/.config/alacritty .config &
cp -r ~/.config/kitty .config &
cp -r ~/.config/htop .config &
cp -r ~/.config/hypr .config &
cp -r ~/.config/i3 .config &
cp -r ~/.config/i3status .config &
cp -r ~/.config/picom .config &
cp -r ~/.config/polybar .config &
cp -r ~/.config/rofi .config &
cp -r ~/.config/wallpapers .config &
cp -r ~/.config/waybar .config &
cp -r ~/.config/fastfetch .config &